### PR TITLE
add contact form

### PR DESCRIPTION
**Pull request by rudicarrilloypr**
## Project requirements
The section you need to build for this milestone is:
the contact form:
Form

- and the footer (if present in the design)
We included a screenshot of Template 1 for reference, but you should follow the template that you chose.

Make sure that:
Name field accepts up to 30 chars.
Email field accepts only emails.
Message field accepts up to 500 chars.
All fields have placeholder text.
All fields have the correct type.
A user cannot submit the form if one or more of the fields is empty.
Collect data by using the [Formspree service](https://formspree.io/html).
In order to lay out the elements on the page you should use flexbox.
You don't need to implement any functionality that requires JavaScript.
You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
Implement the button interactions (enable, hover, etc.).
The website should be responsive, following these breakpoints:
Minimum mobile screen size should be 375px
Minimum desktop screen size should be 768px
Use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels

### CODE REVIEW

**Review by LionRouge1 — COMMENTED** [review]
Hi @rudicarrilloypr, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is supposed to be a pair- programming activity, but you're the only one who committed to this project. Kindly make sure you work with your partner to submit this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by rudicarrilloypr** [comment]
@LionRouge1 all right, so we have to submit the project at the same time or what should I do?

**Comment by rudicarrilloypr** [comment]
@Fernando426 made some corrections to index.html on our pair-programming schedule.

**Comment by LionRouge1** [comment]
Hi @rudicarrilloypr, your partner have to commit to your project and push his work to this repo

**Review by LionRouge1 — COMMENTED** [review]
Hi @rudicarrilloypr, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is supposed to be a pair- programming activity, but you're the only one who committed to this project. Kindly make sure you work with your partner to submit this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Pull request closed without merging**
