### PR TITLE
add collaborator

### PR DESCRIPTION
**Pull request by rudicarrilloypr**
### Project requirements

_**IMPORTANT NOTE:** For each Microverse project, you need to create a separate pull request. [Read how to work with multiple pull requests in your one repository in the most efficient way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/multiple_pull_requests.md)._

- The section you need to build for this milestone is: 
    - the contact form:
    <p align="center">
     Form
    </p>
    - and the footer (if present in the design)
We included a screenshot of Template 1 for reference, but you should follow the template that you chose.
- Make sure that:
    - Name field accepts **up to 30 chars**.
    - Email field accepts **only emails**.
    - Message field accepts **up to 500 chars**.
    - All fields have **placeholder text**.
    - All fields have the **correct type**.
    - A user cannot submit the form if one or more of the fields is empty.
- Collect data by using the [Formspree service](https://formspree.io/html).
- In order to lay out the elements on the page you should use **flexbox**.
- You **don't** need to implement any functionality that requires JavaScript.
- You must **stick to the design as much as possible** (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
- Implement the **button interactions** (enable, hover, etc.).
- The website should be **responsive**, following these breakpoints:
    - Minimum mobile screen size should be `375px`
    - Minimum desktop screen size should be `768px`
- Use **responsive values in your CSS rules**, like percentages (i.e. `width: 80%`), instead of pixels

### CODE REVIEW

**Review by IngDavidTM — CHANGES_REQUESTED** [review]
Hi @rudicarrilloypr  🙋‍♂️, 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code

## :no_entry:  Invalid Code Review Request :no_entry: 

- [x] You have submitted a project, that is supposed to be a pair-programming activity, but you're the only one who committed to this project. Kindly make sure you work with your partner to submit this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready :inbox_tray: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rudicarrilloypr** [comment]
@IngDavidTM hi! my pair programming partner already added his commits, he is also in the participants tab too, I don't know what else I have to do to get this done

**Comment by IngDavidTM** [comment]
> @IngDavidTM hi! my pair programming partner already added his commits, he is also in the participants tab too, I don't know what else I have to do to get this done

Hi @rudicarrilloypr, you should add your commit also to proceed with the review :+1:

**Comment by rudicarrilloypr** [comment]
@IngDavidTM well this is my project, the rest of the commits are mine, or what commit are you talking about?

**Comment by IngDavidTM** [comment]
> @IngDavidTM well this is my project, the rest of the commits are mine, or what commit are you talking about?

To evaluate that both of you have worked in this branch you should add commits for the same branch  (add-collaborator). I noticed that you have added some commits on the last pull request but this is a new branch :+1:.

**Comment by rudicarrilloypr** [comment]
@IngDavidTM oh ok I understand, I already added my commit on this branch

**Review by IngDavidTM — CHANGES_REQUESTED** [review]
## Hi @rudicarrilloypr  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!



## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] Although you have done an excellent job :+1:, it is necessary to ensure that you adhere to the Figma template as closely as possible, as it is a requirement for this project. Therefore, please use the same text color as the template. It is important to follow the Figma template because it maintains consistency in the design and ensures that the project meets the desired aesthetic and functionality standards :+1:.

**Your design**

Screenshot from 2023-05-09 17-06-03

**Figma**

Screenshot from 2023-05-09 17-06-14

- [x] To ensure that the project design matches the Figma template, please use the same design for the submit button, including the text color. This is important because consistency in design elements helps to create a cohesive look and feel for the project :+1:.

**Your design**

Screenshot from 2023-05-09 17-10-51

**Figma**

Screenshot from 2023-05-09 17-11-05


- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by IngDavidTM — APPROVED** [review]
Hi @rudicarrilloypr 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
